### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by santiago-blanco-a3sec** [mpasternak/django-password-policies#17]
I have installed django-password-policies-iplweb 0.8.2 version using pip

```
Collecting django-password-policies-iplweb==0.8.2
  Downloading django_password_policies_iplweb-0.8.2-py3-none-any.whl (177 kB)
```

and it seems that some migrations have to be done:

```
Migrations for 'password_policies':
  /usr/local/lib/python3.7/site-packages/password_policies/migrations/0003_auto_20210713_1349.py
    - Alter field created on passwordprofile
    - Alter field last_changed on passwordprofile
```

This seems it affects to 0.8.3 version, develop and master branches too.

Environment:
- Debian 10 (buster)
- Python 3.7
- Django 2.2

**Comment by mpasternak** [comment]
Confirmed. Are you going to submit a pull request?

**Comment by santiago-blanco-a3sec** [comment]
ok

**Comment by santiago-blanco-a3sec** [comment]
https://github.com/iplweb/django-password-policies-iplweb/pull/18

done

**Comment by mpasternak** [comment]
Commited, thanks!

**Comment by santiago-blanco-a3sec** [comment]
> Commited, thanks!

Are you planning to release a new version on PyPI soon?

**Comment by mpasternak** [comment]
Of course. Perhaps even today evening. I'll let you know.

**Comment by santiago-blanco-a3sec** [comment]
> Of course. Perhaps even today evening. I'll let you know.

Thank you!
