### ISSUE TITLE
Use deprecated functions

### ISSUE THREAD

**Issue by ehooo** [mpasternak/django-password-policies#27]
In Django 3.0 [deprecates](https://docs.djangoproject.com/en/3.0/releases/3.0/#id3) functions ugettext_lazy and ungettext

**Comment by mpasternak** [comment]
Thank you very much for this patch. I'll gladly merge this as soon as I get the tests (via GitHub Actions) working again. Unless somebody would like to add this? There's that tox-gh-actions package that does this kind of automatically...

**Comment by mpasternak** [comment]
Commited, thanks.
