### ISSUE TITLE
User “Zero-cost” exceptions

### ISSUE THREAD

**Issue by ehooo** [mpasternak/django-password-policies#29]
In python 3.11 are implemented a performance for try blocks:
* “Zero-cost” exceptions are implemented, eliminating the cost of [try](https://docs.python.org/3/reference/compound_stmts.html#try) statements when no exception is raised. (Contributed by Mark Shannon in [bpo-40222](https://bugs.python.org/issue?@action=redirect&bpo=40222).)

On the PR  #28 the way that manage the Django 3.0 deprecation imports are not use this performance.
We need to reorder the importation in the try block to use that improve.

**Comment by ehooo** [comment]
@mpasternak i will do when i have time

**Comment by mpasternak** [comment]
Hello Victor! How are you? 

Thanks for letting me know, I did not know about that optimization. Let me know when you have a patch ready. Thanks!

**Comment by mpasternak** [comment]
Merged, thanks!
