### ISSUE TITLE
is_authenticated() should be replaced with is_authenticated in django >= 1.10

### ISSUE THREAD

**Issue by Brandhor** [mpasternak/django-password-policies#3]
https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated

https://github.com/iplweb/django-password-policies-iplweb/blob/master/password_policies/views.py#L35

**Comment by mpasternak** [comment]
Sure it should! Please submit a patch and a test case and reopen.
