### ISSUE TITLE
Shallow Documentation

### ISSUE THREAD

**Issue by fradrick** [mpasternak/django-password-policies#31]
I have come across this package a fork from the original package hopping to see the changes that have been implemented from the original project. However, there is harly any documentation. The original project is no longer compatible with the latest django packages.

Can you assist on how to install and configure this package on a django project. I am currently on django 5.0.1

**Comment by mpasternak** [comment]
Patches accepted

**Comment by fradrick** [comment]
You haven't responded to the issue raised, yet you have closed the case. Kindly point to there documentation which shows how configurations should be implemented.

**Comment by mpasternak** [comment]
Sorry I’m unable to help you ATM. 

Patches accepted means that if you will be able to fix the problem if any I will gladly merge those changes so the others won’t have to do this.
