### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by iriszsy** [mpasternak/django-password-policies#32]
I have install it use pip and then put it in the “installed apps” in settings.py.
I can see it in Admin , but how can it be effect?
![image](https://github.com/iplweb/django-password-policies-iplweb/assets/73436747/86a4c9e2-acbb-4e6f-beef-fb6c132a5785)

**Comment by mikemanger** [comment]
For anyone else looking there is some documentation located on this page

https://iplweb.github.io/django-password-policies-iplweb/

Note it is a bit out of date and uses the original package name. The required PickleSerializer has also being removed from Django 5.
